# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\"*\n\x12SessionInitRequest\x12\x14\n\x0cnum_requests\x18\x01 \x01(\x05\"&\n\x13SessionInitResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\".\n\x10InferenceRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06tensor\x18\x02 \x01(\x0c\"/\n\x11InferenceResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\t2\x8a\x01\n\x10InferenceService\x12>\n\x11InitializeSession\x12\x13.SessionInitRequest\x1a\x14.SessionInitResponse\x12\x36\n\rSendInference\x12\x11.InferenceRequest\x1a\x12.InferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSIONINITREQUEST']._serialized_start=17
  _globals['_SESSIONINITREQUEST']._serialized_end=59
  _globals['_SESSIONINITRESPONSE']._serialized_start=61
  _globals['_SESSIONINITRESPONSE']._serialized_end=99
  _globals['_INFERENCEREQUEST']._serialized_start=101
  _globals['_INFERENCEREQUEST']._serialized_end=147
  _globals['_INFERENCERESPONSE']._serialized_start=149
  _globals['_INFERENCERESPONSE']._serialized_end=196
  _globals['_INFERENCESERVICE']._serialized_start=199
  _globals['_INFERENCESERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
