# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class SplitServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeSession = channel.unary_unary(
                '/SplitService/InitializeSession',
                request_serializer=service__pb2.SessionInitRequest.SerializeToString,
                response_deserializer=service__pb2.SessionInitResponse.FromString,
                _registered_method=True)
        self.SplitCompute = channel.stream_stream(
                '/SplitService/SplitCompute',
                request_serializer=service__pb2.SplitRequest.SerializeToString,
                response_deserializer=service__pb2.SplitResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/SplitService/GetMetrics',
                request_serializer=service__pb2.MetricsRequest.SerializeToString,
                response_deserializer=service__pb2.Metrics.FromString,
                _registered_method=True)


class SplitServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SplitCompute(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SplitServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeSession': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeSession,
                    request_deserializer=service__pb2.SessionInitRequest.FromString,
                    response_serializer=service__pb2.SessionInitResponse.SerializeToString,
            ),
            'SplitCompute': grpc.stream_stream_rpc_method_handler(
                    servicer.SplitCompute,
                    request_deserializer=service__pb2.SplitRequest.FromString,
                    response_serializer=service__pb2.SplitResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=service__pb2.MetricsRequest.FromString,
                    response_serializer=service__pb2.Metrics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SplitService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SplitService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SplitService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SplitService/InitializeSession',
            service__pb2.SessionInitRequest.SerializeToString,
            service__pb2.SessionInitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SplitCompute(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/SplitService/SplitCompute',
            service__pb2.SplitRequest.SerializeToString,
            service__pb2.SplitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SplitService/GetMetrics',
            service__pb2.MetricsRequest.SerializeToString,
            service__pb2.Metrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
