# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class SplitServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SplitCompute = channel.unary_unary(
                '/SplitService/SplitCompute',
                request_serializer=service__pb2.SplitRequest.SerializeToString,
                response_deserializer=service__pb2.SplitResponse.FromString,
                )


class SplitServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SplitCompute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SplitServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SplitCompute': grpc.unary_unary_rpc_method_handler(
                    servicer.SplitCompute,
                    request_deserializer=service__pb2.SplitRequest.FromString,
                    response_serializer=service__pb2.SplitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SplitService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SplitService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SplitCompute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SplitService/SplitCompute',
            service__pb2.SplitRequest.SerializeToString,
            service__pb2.SplitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
